### ISSUE TITLE
Expor to database

### ISSUE THREAD

**Issue by digodox** [NewOrdered/TagManagerPublic#1]
Hi Anton.

Nice Project. For us that use Intouch is realy usefull.
Are you reading the Tagname.X and .NDX files to open the tagname dictionary? Or is there any other way?

Can I run this application with the Intouch also running?

I was wondering if it would be possible to export the tagname dictionary directly into an SQL database.

**Comment by NewOrdered** [comment]
I use .CSV files (dumps) created by InTouch. I assumed that Tagname.X and .NDX are proprietory formats. But I never got into any specifics with them actually.

> Can I run this application with the Intouch also running?
Absolutely.

**Comment by NewOrdered** [comment]
@digodox 
> I was wondering if it would be possible to export the tagname dictionary directly into an SQL database.

Could you please provide more details? Which DB and what is it for?

**Comment by NewOrdered** [comment]
BTW this public repository is for demonstation puproses, it is not up-to-date, If you want latest version I can send you invite to private repository.

**Comment by zanex88** [comment]
Hi NewOrdered. I'am very interested in the latest version. So I'd be happy to get access to the latest version. Thank you very much... :)

**Comment by NewOrdered** [comment]
> Hi NewOrdered. I'am very interested in the latest version. So I'd be happy to get access to the latest version. Thank you very much... :)

Just curious
Are you a SCADA developer? Do you work with Wonderware products?

**Comment by zanex88** [comment]
Hi,
I'm an engineer for automation. We work with Siemens Wincc, TIA, PCS7, Wonderware (IDE or InTouch) and alsmost anything else. :) Just found that Git and the screenshots are looking promising compared to tag editor in intouch or editing CSVs. ;)

**Comment by NewOrdered** [comment]
> Hi, I'm an engineer for automation. We work with Siemens Wincc, TIA, PCS7, Wonderware (IDE or InTouch) and alsmost anything else. :) Just found that Git and the screenshots are looking promising compared to tag editor in intouch or editing CSVs. ;)

I added you to the actual repository. Please provide all feedback there.
This item is closed.
